<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?
$aMenuLinks = Array(
    Array(
        "Продукты",
        "",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Tacticum Platform",
        "/platform/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Tacticum Agents",
        "/agents/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Tacticum Dev",
        "/dev/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Tacticum Forum",
        "/forum/",
        Array(),
        Array(),
        ""
    ),
	Array(
		"Внедрение",
		"",
		Array(), 
		Array(), 
		"" 
	),
	Array(
        "Услуги",
        "/services/",
        Array(),
        Array(),
        ""
    ),
	Array(
        "Собрать команду",
        "/price/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Примеры расчетов",
        "/offer/",
        Array(),
        Array(),
        ""
    ),
	Array(
		"AI-калькулятор",
		"/calculator/",
		Array(),
		Array(),
		""
	),
	Array(
		"AI-боты",
		"/aiagents/",
		Array(),
		Array(),
		""
	),
    Array(
        "Компания",
        "",
        Array(),
        Array(),
        ""
    ),
	Array(
        "О нас",
        "/about/#about-company",
        Array(),
        Array(),
        ""
    ),
	Array(
        "Команда",
        "/about/#team",
        Array(),
        Array(),
        ""
    ),
	Array(
        "Карьера",
        "/about/#careers",
        Array(),
        Array(),
        ""
    ),
	Array(
        "Партнеры",
        "/about/#partners",
        Array(),
        Array(),
        ""
    )
);
?>
